/*
 * ws2812.c
 * WS2812 Driver Implementation — MSPM0G3507
 *
 * Hardware path:
 *   gPwmBuffer[] ──DMA Ch0──► TIMA1 CC0 register ──► PA15 (PINCM37)
 *
 * SYSCFG_DL_init() (called in main before WS2812_Init) handles:
 *   • 80 MHz MCLK via SYSPLL
 *   • PA15 IOMUX → TIMA1_CCP0
 *   • TIMA1 PWM edge-aligned, ARR=99, CC0=0
 *   • DMA Ch0 config (gTIMA1_CCP0Config), interrupt enabled
 */

#include "ws2812.h"
#include <string.h>

//Added from comment about main.c
//extern const DL_DMA_Config gTIMA0_CCP0Config;

//Added since gTIMA0_CCP0Config can't be accessed outside ti_msp_dl_config.c
static const DL_DMA_Config gWS2812_DMAConfig = {
    .transferMode   = DL_DMA_SINGLE_TRANSFER_MODE,
    .extendedMode   = DL_DMA_NORMAL_MODE,
    .destIncrement  = DL_DMA_ADDR_UNCHANGED,
    .srcIncrement   = DL_DMA_ADDR_INCREMENT,
    .destWidth      = DL_DMA_WIDTH_HALF_WORD,
    .srcWidth       = DL_DMA_WIDTH_HALF_WORD,
    .trigger        = DMA_CH_0_TRIG,
    .triggerType    = DL_DMA_TRIGGER_TYPE_INTERNAL,
};

/* ── Private State ──────────────────────────────────────────────────── */

/* One uint16_t per bit encodes the CCR duty value for that bit */
static volatile uint16_t gPwmBuffer[WS2812_BUF_SIZE];

/* LED colour storage in GRB order: [index][G, R, B] */
static uint8_t gLedData[WS2812_MAX_LEDS][3];

static uint8_t  gNumLEDs    = WS2812_MAX_LEDS;
static uint8_t  gBrightness = 255;
static volatile bool gTransferDone = false;

/* ── Private: build PWM duty-cycle buffer ───────────────────────────── */
static void buildPwmBuffer(void)
{
    uint32_t idx = 0;

    for (uint8_t led = 0; led < gNumLEDs; led++)
    {
        uint8_t g = gLedData[led][0];
        uint8_t r = gLedData[led][1];
        uint8_t b = gLedData[led][2];

#if WS2812_USE_BRIGHTNESS
        g = (uint8_t)(((uint16_t)g * gBrightness) >> 8);
        r = (uint8_t)(((uint16_t)r * gBrightness) >> 8);
        b = (uint8_t)(((uint16_t)b * gBrightness) >> 8);
#endif

        /* WS2812 expects GRB, MSB first */
        uint32_t color = ((uint32_t)g << 16) |
                         ((uint32_t)r <<  8) |
                         (uint32_t)b;

        for (int8_t bit = 23; bit >= 0; bit--)
        {
            gPwmBuffer[idx++] =
                (color & (1u << bit)) ? WS2812_CCR_HI : WS2812_CCR_LO;
        }
    }

    /* Reset pulse: 50 zero-duty slots = 62.5 µs LOW */
    for (uint8_t i = 0; i < WS2812_RESET_SLOTS; i++)
        gPwmBuffer[idx++] = 0u;
}

/* ── Public API ─────────────────────────────────────────────────────── */

void WS2812_Init(void)
{
    /*
     * SYSCFG_DL_init() has already configured:
     *   TIMA1 PWM (ARR=99, CC0=0, edge-aligned, stopped)
     *   DMA Ch0   (gTIMA1_CCP0Config, interrupt enabled)
     *   PA15      (IOMUX_PINCM37 → TIMA1_CCP0)
     *   MCLK      (80 MHz via SYSPLL)
     *
     * We only need to fix the DMA destination address to point at
     * TIMA1's CC0 capture-compare register, and clear the buffers.
     *
     * TIMA1->COUNTERREGS.CC_01[0] is the 16-bit CC0 load register.
     */
    DL_DMA_setDestAddr(DMA, TIMA0_CCP0_CHAN_ID,
                       (uint32_t)&TIMA1->COUNTERREGS.CC_01[0]);

    memset((void *)gPwmBuffer, 0, sizeof(gPwmBuffer));
    memset(gLedData,           0, sizeof(gLedData));
}

/* ─────────────────────────────────────────────────────────────────── */

void WS2812_SetLED(uint8_t ledIndex, uint8_t r, uint8_t g, uint8_t b)
{
    if (ledIndex >= WS2812_MAX_LEDS) return;
    gLedData[ledIndex][0] = g;
    gLedData[ledIndex][1] = r;
    gLedData[ledIndex][2] = b;
}

/* ─────────────────────────────────────────────────────────────────── */

void WS2812_SetBrightness(uint8_t brightness)
{
    gBrightness = brightness;
}

/* ─────────────────────────────────────────────────────────────────── */

void WS2812_SetNumLEDs(uint8_t count)
{
    if (count > WS2812_MAX_LEDS) count = WS2812_MAX_LEDS;
    gNumLEDs = count;
}

/* ─────────────────────────────────────────────────────────────────── */

void WS2812_Send(void)
{
    /* 1. Encode current LED data into PWM duty-cycle buffer */
    buildPwmBuffer();

    uint32_t totalSlots = (uint32_t)(24u * gNumLEDs) + WS2812_RESET_SLOTS;

    /* 2. Reconfigure DMA for this transmission */
    DL_DMA_disableChannel(DMA, TIMA0_CCP0_CHAN_ID);

    DL_DMA_setSrcAddr(DMA, TIMA0_CCP0_CHAN_ID,
                      (uint32_t)gPwmBuffer);
    DL_DMA_setTransferSize(DMA, TIMA0_CCP0_CHAN_ID, totalSlots);

    /* 3. Re-initialise channel to reset internal DMA state machine.
     *    gTIMA1_CCP0Config is the const struct generated by SysConfig. */
    DL_DMA_initChannel(DMA, TIMA0_CCP0_CHAN_ID,
                       (DL_DMA_Config *)&gWS2812_DMAConfig);

    /*DL_DMA_initChannel(DMA, TIMA0_CCP0_CHAN_ID,
                       (DL_DMA_Config *)&gTIMA0_CCP0Config);*/

    /* 4. Clear flag, enable DMA, start timer */
    gTransferDone = false;
    DL_DMA_enableChannel(DMA, TIMA0_CCP0_CHAN_ID);
    DL_TimerA_startCounter(TIMA1);

    /* 5. Wait for ISR to signal completion (CPU sleeps between IRQs) */
    while (!gTransferDone)
    {
        __WFI();
    }
    /* Timer stopped inside ISR; PA15 held LOW by final zero-CCR slots */
}

/* ─────────────────────────────────────────────────────────────────── */

void WS2812_DMA_IRQHandler(void)
{
    if (DL_DMA_getPendingInterrupt(DMA) == DL_DMA_EVENT_IIDX_DMACH0)
    {
        DL_DMA_clearInterruptStatus(DMA, DL_DMA_INTERRUPT_CHANNEL0);
        DL_TimerA_stopCounter(TIMA1);   /* Stop timer, hold PA15 LOW */
        gTransferDone = true;
    }
}